# Generated by Django 3.0 on 2020-02-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=664, null=True)),
                ('school_code', models.CharField(max_length=664, null=True)),
                ('user_name', models.CharField(max_length=664, null=True)),
                ('login_id', models.CharField(max_length=664, null=True)),
                ('contact_no', models.CharField(max_length=12, null=True, unique=True)),
                ('school_email', models.EmailField(max_length=254, null=True)),
                ('alternative_school_email', models.EmailField(max_length=254, null=True)),
                ('address', models.TextField(null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=664, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('admission_no', models.IntegerField(null=True)),
                ('contact_no', models.CharField(max_length=12, null=True, unique=True)),
                ('father_name', models.CharField(max_length=664, null=True)),
                ('mother_name', models.CharField(max_length=664, null=True)),
                ('parent_email', models.EmailField(max_length=254, null=True)),
                ('parent_contact_no', models.CharField(max_length=612, null=True)),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('O', 'O'), ('AB', 'AB')], default='B', max_length=620, null=True)),
                ('category', models.CharField(choices=[('science', 'science'), ('math', 'math'), ('biology', 'biology'), ('physics', 'physics'), ('chemistry', 'chemistry')], max_length=620, null=True)),
                ('religion', models.CharField(choices=[('hindu', 'hindu'), ('muslim', 'muslim'), ('christian', 'christian'), ('other', 'other')], default='hindu', max_length=600, null=True)),
                ('pincode', models.CharField(max_length=6, null=True)),
                ('classes', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=600, null=True)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=600, null=True)),
                ('address', models.TextField(null=True)),
                ('permanent_address', models.TextField(null=True)),
                ('pic', models.FileField(upload_to='')),
            ],
        ),
    ]
