# Generated by Django 3.0 on 2020-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooladmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=664, null=True)),
                ('contact_no', models.CharField(max_length=12, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('msg', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='index',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='category',
            field=models.CharField(choices=[('science', 'science'), ('math', 'math'), ('biology', 'biology'), ('physics', 'physics'), ('chemistry', 'chemistry')], default='math', max_length=620, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
